defmodule Pathika.Names do
  @worlds "Abarra,
    Guparta,
    Koyo Isu,
    Bozeg,
    Phodai,
    Teraat,
    Qabis,
    Chakiragar,
    Tismin Insu,
    Kalmoro,
    Ethar,
    Kotelga,
    Altaxa,
    Nebay,
    Nebayanat,
    Aamidal,
    Standing,
    Bhidra,
    Oret Soi,
    Sudarai,
    Bhojo Patal,
    Matra Dhor,
    Niyat Dhor,
    Grahisa,
    Kono Manoi,
    Turagai,
    Jamosom,
    Ekanga,
    Desh,
    Yaburah,
    Tsugge,
    Harai,
    Rumid,
    Siur,
    Ksu,
    Vo,
    Su,
    Kusaslu,
    Bhanusri,
    Nasiraat,
    Santhe,
    Sestab,
    Kano Insu,
    Kusequ,
    Kanoyariya,
    Turaatrah,
    Guparahid,
    Joyen Bor,
    Bozala,
    Pachorubna,
    Bodempur,
    Gazabul Wa"

  @spec random_world_name :: binary
  def random_world_name do
    @worlds |> String.split(",") |> Enum.random() |> String.trim()
  end
end
